import { describe, expect, it } from 'vitest'

import { canonicalRecord, hashCanonical, hashRecord } from './hash.ts'

/**
 * Vectors generated by running Underlay's own `src/lib/core/hash.ts` (node:crypto)
 * against these inputs. If any of these fail, our Web Crypto port has drifted and
 * commits would re-upload every record instead of just the changed ones.
 */
const VECTORS = [
  {
    input: { id: 'r1', type: 'Preprint', data: { title: 'Hello', zeta: 1, alpha: [3, 2, 1] } },
    canonical: '{"id":"r1","type":"Preprint","data":{"alpha":[3,2,1],"title":"Hello","zeta":1}}',
    hash: '2eab4727daedc103e05710c5195c117a6252d03451cb0cc19b169f8620fc7d00',
  },
  {
    input: { id: 'r2', type: 'Preprint', data: { alpha: [3, 2, 1], zeta: 1, title: 'Hello' } },
    canonical: '{"id":"r2","type":"Preprint","data":{"alpha":[3,2,1],"title":"Hello","zeta":1}}',
    hash: '26d3681508e92362ae8c1ab505975d4aadf2aee9f8e69b69d6244de48ce164aa',
  },
  {
    input: {
      id: 'r3',
      type: 'T',
      data: { nested: { b: { d: 4, c: 3 }, a: 1 }, nil: null, f: 1.5, n: 0 },
    },
    canonical:
      '{"id":"r3","type":"T","data":{"f":1.5,"n":0,"nested":{"a":1,"b":{"c":3,"d":4}},"nil":null}}',
    hash: 'b4f8bb29ca10177e388405bbb593a298a2d7feb639d9235729b0be2540639d6c',
  },
  {
    input: { id: 'r4', type: 'T', data: {} },
    canonical: '{"id":"r4","type":"T","data":{}}',
    hash: 'caab92ab974c6335cdf351c26f199a8dd45b2ba94202c09648f245c0a11dcb0c',
  },
]

describe('hashRecord', () => {
  for (const v of VECTORS) {
    it(`matches Underlay for ${v.input.id}`, async () => {
      const { hash, canonical } = await hashRecord(v.input)
      expect(canonical).toBe(v.canonical)
      expect(hash).toBe(v.hash)
    })
  }

  it('sorts data keys but preserves the id/type/data envelope order', () => {
    expect(canonicalRecord({ id: 'x', type: 'T', data: { b: 1, a: 2 } })).toBe(
      '{"id":"x","type":"T","data":{"a":2,"b":1}}',
    )
  })

  it('is insensitive to input key order inside data', async () => {
    const a = await hashRecord({ id: 'same', type: 'T', data: { x: 1, y: 2 } })
    const b = await hashRecord({ id: 'same', type: 'T', data: { y: 2, x: 1 } })
    expect(a.hash).toBe(b.hash)
  })

  it('hashCanonical agrees with hashRecord', async () => {
    const { hash, canonical } = await hashRecord(VECTORS[0]!.input)
    expect(await hashCanonical(canonical)).toBe(hash)
  })
})
